"""add columns

Revision ID: 205725ad9992
Revises: 
Create Date: 2017-10-28 20:46:13.765685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205725ad9992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_exchanges', sa.Column('meta_description', sa.String(length=255), nullable=True))
    op.add_column('stock_exchanges', sa.Column('meta_tags', sa.String(length=255), nullable=True))
    op.add_column('stock_exchanges', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'stock_exchanges', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_exchanges', type_='unique')
    op.drop_column('stock_exchanges', 'slug')
    op.drop_column('stock_exchanges', 'meta_tags')
    op.drop_column('stock_exchanges', 'meta_description')
    # ### end Alembic commands ###
