"""add column

Revision ID: 8b93268c8b59
Revises: 205725ad9992
Create Date: 2017-10-31 21:20:37.947996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b93268c8b59'
down_revision = '205725ad9992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_exchanges', sa.Column('type', sa.String(length=45), nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('stock_exchanges', 'type')
    # ### end Alembic commands ###
