"""empty message

Revision ID: 9c84e07108b0
Revises: 
Create Date: 2017-10-31 09:29:57.587339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c84e07108b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.add_column('stock_exchanges', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('stock_exchanges', sa.Column('meta_tags', sa.String(length=255), nullable=True))
    op.add_column('stock_exchanges', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'stock_exchanges', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_exchanges', type_='unique')
    op.drop_column('stock_exchanges', 'slug')
    op.drop_column('stock_exchanges', 'meta_tags')
    op.drop_column('stock_exchanges', 'meta_description')
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
